# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_frame.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QMenu,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)
import icon_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(728, 331)
        self.actionCliente = QAction(MainWindow)
        self.actionCliente.setObjectName(u"actionCliente")
        self.actionFornecedor = QAction(MainWindow)
        self.actionFornecedor.setObjectName(u"actionFornecedor")
        self.actionUsuario = QAction(MainWindow)
        self.actionUsuario.setObjectName(u"actionUsuario")
        self.actionVenda = QAction(MainWindow)
        self.actionVenda.setObjectName(u"actionVenda")
        self.actionConsumo_de_produtos = QAction(MainWindow)
        self.actionConsumo_de_produtos.setObjectName(u"actionConsumo_de_produtos")
        self.actionSaldo = QAction(MainWindow)
        self.actionSaldo.setObjectName(u"actionSaldo")
        self.actionCompra = QAction(MainWindow)
        self.actionCompra.setObjectName(u"actionCompra")
        self.actionPedido = QAction(MainWindow)
        self.actionPedido.setObjectName(u"actionPedido")
        self.actionCancelar = QAction(MainWindow)
        self.actionCancelar.setObjectName(u"actionCancelar")
        self.actionCaixa = QAction(MainWindow)
        self.actionCaixa.setObjectName(u"actionCaixa")
        self.actionBancos = QAction(MainWindow)
        self.actionBancos.setObjectName(u"actionBancos")
        self.actionCantas_pagar = QAction(MainWindow)
        self.actionCantas_pagar.setObjectName(u"actionCantas_pagar")
        self.actionContas_Receber = QAction(MainWindow)
        self.actionContas_Receber.setObjectName(u"actionContas_Receber")
        self.actionContas_Recebidas = QAction(MainWindow)
        self.actionContas_Recebidas.setObjectName(u"actionContas_Recebidas")
        self.actionGeral = QAction(MainWindow)
        self.actionGeral.setObjectName(u"actionGeral")
        self.actionResumido = QAction(MainWindow)
        self.actionResumido.setObjectName(u"actionResumido")
        self.actionGeral_2 = QAction(MainWindow)
        self.actionGeral_2.setObjectName(u"actionGeral_2")
        self.actionResumo = QAction(MainWindow)
        self.actionResumo.setObjectName(u"actionResumo")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lb_logoEmpresa = QLabel(self.centralwidget)
        self.lb_logoEmpresa.setObjectName(u"lb_logoEmpresa")
        self.lb_logoEmpresa.setGeometry(QRect(150, 130, 391, 191))
        self.lb_logoEmpresa.setStyleSheet(u"\n"
"background-image: url(:/icons/icons/logo_empresa_original.png);")
        self.bt_cliente = QPushButton(self.centralwidget)
        self.bt_cliente.setObjectName(u"bt_cliente")
        self.bt_cliente.setGeometry(QRect(0, 0, 81, 71))
        self.bt_cliente.setMinimumSize(QSize(60, 30))
        self.bt_cliente.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon = QIcon()
        icon.addFile(u":/icons/icons/cliente.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_cliente.setIcon(icon)
        self.bt_cliente.setIconSize(QSize(60, 60))
        self.bt_fornecedor = QPushButton(self.centralwidget)
        self.bt_fornecedor.setObjectName(u"bt_fornecedor")
        self.bt_fornecedor.setGeometry(QRect(80, 0, 81, 71))
        self.bt_fornecedor.setMinimumSize(QSize(60, 30))
        self.bt_fornecedor.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/fornecedor.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_fornecedor.setIcon(icon1)
        self.bt_fornecedor.setIconSize(QSize(60, 60))
        self.bt_produtos = QPushButton(self.centralwidget)
        self.bt_produtos.setObjectName(u"bt_produtos")
        self.bt_produtos.setGeometry(QRect(160, 0, 81, 71))
        self.bt_produtos.setMinimumSize(QSize(60, 30))
        self.bt_produtos.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/produtos.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_produtos.setIcon(icon2)
        self.bt_produtos.setIconSize(QSize(60, 60))
        self.bt_vendas = QPushButton(self.centralwidget)
        self.bt_vendas.setObjectName(u"bt_vendas")
        self.bt_vendas.setGeometry(QRect(240, 0, 81, 71))
        self.bt_vendas.setMinimumSize(QSize(60, 30))
        self.bt_vendas.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/venda.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_vendas.setIcon(icon3)
        self.bt_vendas.setIconSize(QSize(60, 60))
        self.bt_pagar = QPushButton(self.centralwidget)
        self.bt_pagar.setObjectName(u"bt_pagar")
        self.bt_pagar.setGeometry(QRect(320, 0, 81, 71))
        self.bt_pagar.setMinimumSize(QSize(60, 30))
        self.bt_pagar.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/contasPagar.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_pagar.setIcon(icon4)
        self.bt_pagar.setIconSize(QSize(60, 60))
        self.bt_bancos = QPushButton(self.centralwidget)
        self.bt_bancos.setObjectName(u"bt_bancos")
        self.bt_bancos.setGeometry(QRect(400, 0, 81, 71))
        self.bt_bancos.setMinimumSize(QSize(60, 30))
        self.bt_bancos.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/banco.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_bancos.setIcon(icon5)
        self.bt_bancos.setIconSize(QSize(60, 60))
        self.bt_receber = QPushButton(self.centralwidget)
        self.bt_receber.setObjectName(u"bt_receber")
        self.bt_receber.setGeometry(QRect(480, 0, 81, 71))
        self.bt_receber.setMinimumSize(QSize(60, 30))
        self.bt_receber.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/receber.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_receber.setIcon(icon6)
        self.bt_receber.setIconSize(QSize(60, 60))
        self.bt_caixa = QPushButton(self.centralwidget)
        self.bt_caixa.setObjectName(u"bt_caixa")
        self.bt_caixa.setGeometry(QRect(560, 0, 81, 71))
        self.bt_caixa.setMinimumSize(QSize(60, 30))
        self.bt_caixa.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/caixa.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_caixa.setIcon(icon7)
        self.bt_caixa.setIconSize(QSize(60, 60))
        self.bt_sair = QPushButton(self.centralwidget)
        self.bt_sair.setObjectName(u"bt_sair")
        self.bt_sair.setGeometry(QRect(640, 0, 81, 71))
        self.bt_sair.setMinimumSize(QSize(60, 30))
        self.bt_sair.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/sair.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.bt_sair.setIcon(icon8)
        self.bt_sair.setIconSize(QSize(60, 60))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 728, 26))
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuOperacoes = QMenu(self.menubar)
        self.menuOperacoes.setObjectName(u"menuOperacoes")
        self.menuSaida_de_produtos = QMenu(self.menuOperacoes)
        self.menuSaida_de_produtos.setObjectName(u"menuSaida_de_produtos")
        self.menuEstoque = QMenu(self.menuOperacoes)
        self.menuEstoque.setObjectName(u"menuEstoque")
        self.menuCompras = QMenu(self.menuOperacoes)
        self.menuCompras.setObjectName(u"menuCompras")
        self.menuFinanceiro = QMenu(self.menubar)
        self.menuFinanceiro.setObjectName(u"menuFinanceiro")
        self.menuConsultas = QMenu(self.menubar)
        self.menuConsultas.setObjectName(u"menuConsultas")
        self.menuVendas = QMenu(self.menuConsultas)
        self.menuVendas.setObjectName(u"menuVendas")
        self.menuConsumo = QMenu(self.menuConsultas)
        self.menuConsumo.setObjectName(u"menuConsumo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuOperacoes.menuAction())
        self.menubar.addAction(self.menuFinanceiro.menuAction())
        self.menubar.addAction(self.menuConsultas.menuAction())
        self.menuCadastro.addAction(self.actionCliente)
        self.menuCadastro.addAction(self.actionFornecedor)
        self.menuCadastro.addAction(self.actionUsuario)
        self.menuOperacoes.addAction(self.menuSaida_de_produtos.menuAction())
        self.menuOperacoes.addAction(self.menuEstoque.menuAction())
        self.menuOperacoes.addAction(self.menuCompras.menuAction())
        self.menuSaida_de_produtos.addAction(self.actionVenda)
        self.menuSaida_de_produtos.addAction(self.actionConsumo_de_produtos)
        self.menuEstoque.addAction(self.actionSaldo)
        self.menuCompras.addAction(self.actionCompra)
        self.menuCompras.addAction(self.actionPedido)
        self.menuCompras.addAction(self.actionCancelar)
        self.menuFinanceiro.addAction(self.actionCaixa)
        self.menuFinanceiro.addAction(self.actionBancos)
        self.menuFinanceiro.addAction(self.actionCantas_pagar)
        self.menuFinanceiro.addAction(self.actionContas_Receber)
        self.menuFinanceiro.addAction(self.actionContas_Recebidas)
        self.menuConsultas.addAction(self.menuVendas.menuAction())
        self.menuConsultas.addAction(self.menuConsumo.menuAction())
        self.menuVendas.addAction(self.actionGeral)
        self.menuVendas.addAction(self.actionResumido)
        self.menuConsumo.addAction(self.actionGeral_2)
        self.menuConsumo.addAction(self.actionResumo)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionCliente.setText(QCoreApplication.translate("MainWindow", u"Cliente", None))
        self.actionFornecedor.setText(QCoreApplication.translate("MainWindow", u"Fornecedor", None))
        self.actionUsuario.setText(QCoreApplication.translate("MainWindow", u"Usuario", None))
        self.actionVenda.setText(QCoreApplication.translate("MainWindow", u"Venda", None))
        self.actionConsumo_de_produtos.setText(QCoreApplication.translate("MainWindow", u"Consumo de produtos", None))
        self.actionSaldo.setText(QCoreApplication.translate("MainWindow", u"Saldo", None))
        self.actionCompra.setText(QCoreApplication.translate("MainWindow", u"Compra", None))
        self.actionPedido.setText(QCoreApplication.translate("MainWindow", u"Pedido", None))
        self.actionCancelar.setText(QCoreApplication.translate("MainWindow", u"Cancelar", None))
        self.actionCaixa.setText(QCoreApplication.translate("MainWindow", u"Caixa", None))
        self.actionBancos.setText(QCoreApplication.translate("MainWindow", u"Bancos", None))
        self.actionCantas_pagar.setText(QCoreApplication.translate("MainWindow", u"Cantas pagar", None))
        self.actionContas_Receber.setText(QCoreApplication.translate("MainWindow", u"Contas Receber", None))
        self.actionContas_Recebidas.setText(QCoreApplication.translate("MainWindow", u"Contas Recebidas", None))
        self.actionGeral.setText(QCoreApplication.translate("MainWindow", u"Geral", None))
        self.actionResumido.setText(QCoreApplication.translate("MainWindow", u"Resumido", None))
        self.actionGeral_2.setText(QCoreApplication.translate("MainWindow", u"Geral", None))
        self.actionResumo.setText(QCoreApplication.translate("MainWindow", u"Resumo", None))
#if QT_CONFIG(whatsthis)
        self.lb_logoEmpresa.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        self.lb_logoEmpresa.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><br/></p></body></html>", None))
        self.bt_cliente.setText("")
        self.bt_fornecedor.setText("")
        self.bt_produtos.setText("")
        self.bt_vendas.setText("")
        self.bt_pagar.setText("")
        self.bt_bancos.setText("")
        self.bt_receber.setText("")
        self.bt_caixa.setText("")
        self.bt_sair.setText("")
        self.menuCadastro.setTitle(QCoreApplication.translate("MainWindow", u"Cadastro", None))
        self.menuOperacoes.setTitle(QCoreApplication.translate("MainWindow", u"Operacoes", None))
        self.menuSaida_de_produtos.setTitle(QCoreApplication.translate("MainWindow", u"Saida de produtos", None))
        self.menuEstoque.setTitle(QCoreApplication.translate("MainWindow", u"Estoque", None))
        self.menuCompras.setTitle(QCoreApplication.translate("MainWindow", u"Compras", None))
        self.menuFinanceiro.setTitle(QCoreApplication.translate("MainWindow", u"Financeiro", None))
        self.menuConsultas.setTitle(QCoreApplication.translate("MainWindow", u"Consultas", None))
        self.menuVendas.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
        self.menuConsumo.setTitle(QCoreApplication.translate("MainWindow", u"Consumo", None))
    # retranslateUi

